### ISSUE TITLE
大会员海外看不了新电影

### ISSUE THREAD

**Issue by langlang19891025** [kghost/bilibili-area-limit#11]
大会员，日本地区，看不了9 10月份出的电影

**Comment by kghost** [comment]
给一个不能看的链接

**Comment by langlang19891025** [comment]
> 给一个不能看的链接
https://www.bilibili.com/bangumi/play/ss28198/?theme=movie 罗小黑战记
https://www.bilibili.com/bangumi/play/ss28818#289130 昆虫总动员2
https://www.bilibili.com/bangumi/play/ss28586#289217 盗梦空间

这3部都是最近上架的，我是大会员，日本地区，都是“无法连接服务器或返回异常。。。。”

**Comment by kghost** [comment]
这些好像视频用的CDN只有国内能访问，所以毫无办法了。

视频体积太大，无法代理。

**Comment by langlang19891025** [comment]
> 这些好像视频用的CDN只有国内能访问，所以毫无办法了。
> 
> 视频体积太大，无法代理。

好的 谢谢你的回复
