### ISSUE TITLE
可不可能实现解除动画疯的限制

### ISSUE THREAD

**Issue by ghost** [kghost/bilibili-area-limit#12]
目前动画疯只能台湾ip才可以看，大佬有办法吗？

**Comment by kghost** [comment]
能否提供一个视频链接？

**Comment by kghost** [comment]
现在是有台湾地区支持的，比如 https://www.bilibili.com/bangumi/play/ep257330

**Comment by ghost** [comment]
> 能否提供一个视频链接？

https://ani.gamer.com.tw/animeVideo.php?sn=14445

**Comment by kghost** [comment]
抱歉,这个只针对B站
