### ISSUE TITLE
可不可以将你的服务器的接口，作为“哔哩漫游”的备用接口？

### ISSUE THREAD

**Issue by yujincheng08** [kghost/bilibili-area-limit#15]
你好，我最近在维护一个安卓版本的看区域限制番剧的xposed模块，目前以biliplus作为主服务器。但是biliplus有时候可能会崩掉（比如现在），而且仅港澳地区和东南亚地区的都不能解析。可否使用您的服务器作为备用？
项目地址https://github.com/yujincheng08/BiliRoaming

**Comment by kghost** [comment]
可以，请随意使用，不过没有任何SLA保证

**Comment by yujincheng08** [comment]
非常感谢！已经添加上去了。
