### ISSUE TITLE
`bilibili-cn-api.kghost.info` 502了

### ISSUE THREAD

**Issue by yujincheng08** [kghost/bilibili-area-limit#23]
`bilibili-cn-api.kghost.info`好像502了。

另外作者能否提供赞助方式？我[模块](https://github.com/yujincheng08/BiliRoaming)这边使用了您的服务器作为备用服务器，希望加上您的赞助方式。

**Comment by kghost** [comment]
OK， 我看看问题

**Comment by kghost** [comment]
修复了
