### ISSUE TITLE
可不可以将你的服务器的接口，作为“解除B站区域限制”脚本的备用接口？

### ISSUE THREAD

**Issue by ipcjs** [kghost/bilibili-area-limit#3]
我在`dev`分支里面试着添加了下，改的不多，可以跑`(°∀°)ﾉ`
https://github.com/ipcjs/bilibili-helper/commit/1135309b2b86b106d3fe451195e15e5e3ee75d1c

**Comment by kghost** [comment]
可以的，不过域名换一下。

香港（加上 -hk）：
https://bilibili-hk-www.kghost.info/
https://bilibili-hk-api.kghost.info/

台湾：
https://bilibili-tw-www.kghost.info/
https://bilibili-tw-api.kghost.info/

还有一个国外访问国内视频的代理：
https://bilibili-cn-www.kghost.info/
https://bilibili-cn-api.kghost.info/

这两个域名可能过几天就删了
bilibili-www.kghost.info
bilibili-api.kghost.info

**Comment by ipcjs** [comment]
合并完成👌：https://github.com/ipcjs/bilibili-helper/commit/986fd37d837aa6ebb8e49e658b70bf5a0e5bf9e6
