### ISSUE TITLE
失效报告，不确定原因。

### ISSUE THREAD

**Issue by MR-Ender** [kghost/bilibili-area-limit#7]
不知道为什么，这个脚本出了一些问题，事实上当他提示我要升级到bata版本的tampermonkey时，我并没有升级为bata版本，但是其依然可以使用，但是在2019年8月17日早上7点40分左右（GMT+8），他失效了，当我满怀欣喜的打开某科学的一方通行港澳台时，呈现给我的只有16秒的肥肠抱歉：），随后我尝试了其他的港澳台番剧，除了16秒的肥肠抱歉外，有的番剧则是直接丢失视频。我尝试了重新安装此脚本，但是依然无济于事。但是有一个特例，其他我尝试的番剧不是丢失就是非常抱歉，唯独炎炎消防队可以正常加载观看，我不知道这是如何做到的：）。
之后我尝试安装了tampermonkey bata版本，将此脚本导出后重新安装在bata版本上，测试后还是一样的情况，炎炎消防队依然一枝独秀，即使多次重新安装此脚本也一样。在测试时我已经卸载了稳定版tampermonkey。并且重启了谷歌Chrone浏览器，还使用了火绒清理了浏览器缓存，但是没有清理cookies，我不知道这会不会影响脚本：）
我并不了解编程：），但是我认为这是个BUG或是因为B站更新了什么东西导致的错误，也可能是墙日渐高了。所以我将他报告给您。

**Comment by kghost** [comment]
昨晚B站更新，导致不能用了，这两天会更新脚本修复。

**Comment by MR-Ender** [comment]
OK，我知道了：）
感谢您愿意制作这个脚本造福我们这些白嫖狗（手动狗头）

**Comment by kghost** [comment]
已修复，请安装新版本
